#!/bin/bash
# ROCm Installation Script
# Generated by install_rocm.py

set -e  # Exit on error

wget https://repo.radeon.com/amdgpu-install/6.2.4/ubuntu/noble/amdgpu-install_6.2.60204-1_all.deb
sudo dpkg -i amdgpu-install_6.2.60204-1_all.deb
sudo apt update
sudo amdgpu-install --usecase=rocm --no-dkms
sudo usermod -a -G render,video $USER
echo "Installation complete! Please reboot your system."
echo "After reboot, run: python scripts/check_backends.py"
